---
- hosts: OSEv3
  name: ensure docker is running
  tasks:
  - name: start docker service
    service:
      enabled: yes
      name: docker
      state: started
  - name: remove all system container
    shell: |
      atomic images delete -af

